version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: group15
      POSTGRES_PASSWORD: group15
      POSTGRES_DB: group15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U group15"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    environment:
      DATABASE_URL: "postgres://group15:group15@db:5432/group15?sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
